/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ventainstrumentosmusicales.gui;

import com.mycompany.ventainstrumentosmusicales.model.AccesorioCuerda;
import com.mycompany.ventainstrumentosmusicales.services.ServicioInstrumentos;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class GUIEditarAccesorioCuerda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIEditarAccesorioCuerda.class.getName());
     private ServicioInstrumentos servicioInstrumentos;
    /**
     * Creates new form GUIEditarViento
     */
    public GUIEditarAccesorioCuerda() {
        initComponents();
        setLocationRelativeTo(this);
        servicioInstrumentos = ServicioInstrumentos.getInstancia();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblId1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroLlaves = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTipoBoquilla = new javax.swing.JTextField();
        btnEditar1 = new javax.swing.JButton();
        ComboBoxTipo = new javax.swing.JComboBox<>();

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");

        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Aun no encontrada");

        btnEditar.setBackground(new java.awt.Color(255, 153, 0));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUIEditarCuerda");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Editar Accesorio de Cuerda");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inserta el ID del accesorio:");

        txtConsulta.addActionListener(this::txtConsultaActionPerformed);

        btnConsultar.setBackground(new java.awt.Color(255, 153, 0));
        btnConsultar.setText("Buscar");
        btnConsultar.addActionListener(this::btnConsultarActionPerformed);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");

        lblId1.setForeground(new java.awt.Color(255, 255, 255));
        lblId1.setText("Aun no encontrada");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio:");

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Marca:");

        txtNumeroLlaves.addActionListener(this::txtNumeroLlavesActionPerformed);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Instrumento:");

        txtTipoBoquilla.addActionListener(this::txtTipoBoquillaActionPerformed);

        btnEditar1.setBackground(new java.awt.Color(255, 153, 0));
        btnEditar1.setText("Guardar cambios");
        btnEditar1.addActionListener(this::btnEditar1ActionPerformed);

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUERDAFROTADA", "CUERDAPULSADA" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnConsultar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblId1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtNumeroLlaves, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtTipoBoquilla, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(ComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar1)
                .addGap(296, 296, 296))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblId1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumeroLlaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTipoBoquilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnEditar1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaActionPerformed
        // Esto simula un clic en el botón Consultar cuando el usuario presiona Enter en el campo de texto
        btnConsultar.doClick();
    }//GEN-LAST:event_txtConsultaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
              String idStr = txtConsulta.getText().trim();
 
    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa el ID del instrumento a buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
 
    try {
        int idConsulta = Integer.parseInt(idStr);
 
        AccesorioCuerda accesorio = servicioInstrumentos.buscarAccesorioCuerda(idConsulta);
 
        if (accesorio != null) {
            // Llenar los campos con los valores del accesorio de cuerda
            lblId1.setText(String.valueOf(accesorio.getId()));
            txtNombre.setText(accesorio.getNombre());
            ComboBoxTipo.setSelectedItem(accesorio.getTipo().toString());
            txtPrecio.setText(String.valueOf(accesorio.getPrecio()));
            txtNumeroLlaves.setText(accesorio.getMarca());
            txtTipoBoquilla.setText(String.valueOf(accesorio.getIdInstrumento()));
            
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ningún accesorio de cuerda con ese ID.", "No Encontrado", JOptionPane.ERROR_MESSAGE);
            // Limpiar los campos 
            lblId1.setText(""); txtNombre.setText(""); ComboBoxTipo.setSelectedIndex(0);
            txtPrecio.setText(""); txtNumeroLlaves.setText(""); txtTipoBoquilla.setText("");
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al buscar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtNumeroLlavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroLlavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroLlavesActionPerformed

    private void txtTipoBoquillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoBoquillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoBoquillaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
     String idConsultaStr = txtConsulta.getText().trim();
    if (idConsultaStr.isEmpty() || lblId1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Primero busca un accesorio válido para editarlo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
 
    try {
        int idOriginal = Integer.parseInt(idConsultaStr);
        
        // Recoger y convertir los valores de los campos
        int idAccesorio = Integer.parseInt(lblId1.getText().trim());
        String nombre = txtNombre.getText().trim();
        String strTipo = (String) ComboBoxTipo.getSelectedItem();
        double precio = Double.parseDouble(txtPrecio.getText().trim());
        String marca = txtNumeroLlaves.getText().trim();
        int idInstrumento = Integer.parseInt(txtTipoBoquilla.getText().trim());
 
        AccesorioCuerda.tipo tipoAccesorio;
        try {
            tipoAccesorio = AccesorioCuerda.tipo.valueOf(strTipo.toUpperCase());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, "El tipo debe ser CUERDAPULSADA o CUERDAFROTADA.", "Tipo inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
 
        // Crear instancia con los nuevos datos del accesorio de cuerda
        AccesorioCuerda accesorioActualizado = new AccesorioCuerda(idAccesorio, nombre, tipoAccesorio, precio, marca, idInstrumento);
     
        // Actualizar usando el servicio
        servicioInstrumentos.actualizarAccesorio(idOriginal, accesorioActualizado);
        
        JOptionPane.showMessageDialog(this, "Accesorio actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Revisa que ID, Precio e ID de Instrumento sean numéricos.", "Error de formato", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // Captura las excepciones de validación, como un ID de instrumento inexistente
        JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEditar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIEditarAccesorioCuerda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroLlaves;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTipoBoquilla;
    // End of variables declaration//GEN-END:variables
}
