/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ventainstrumentosmusicales.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();
        menuInstrumentoCuerda = new javax.swing.JMenu();
        menuItemAdicionarCuerda = new javax.swing.JMenuItem();
        menuItemListarCuerda = new javax.swing.JMenuItem();
        menuItemConsultarCuerda = new javax.swing.JMenuItem();
        menuItemEliminarCuerda = new javax.swing.JMenuItem();
        menuItemEditarInstrumentoCuerda = new javax.swing.JMenuItem();
        menuInstrumentoViento = new javax.swing.JMenu();
        menuItemAdicionarViento = new javax.swing.JMenuItem();
        menuItemListarViento = new javax.swing.JMenuItem();
        menuItemConsultarViento = new javax.swing.JMenuItem();
        menuItemEliminarViento = new javax.swing.JMenuItem();
        menuItemEditarViento = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuItemAutores = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUIPrincipal");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 2, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO A");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("VENTA DE INSTRUMENTOS MUSICALES");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/ventainstrumentosmusicales/assets/logoGUIPrincipal.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 3, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("¿Eres fanatico de los Instrumentos Musicales?");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nuestro software te permite llevar el control de tus instrumentos de viento ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("y cuerda de manera práctica y sin complicaciones.");

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(19, 19, 19))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(400, 400, 400)
                                        .addComponent(jLabel6)))))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/ventainstrumentosmusicales/assets/font GUI (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuArchivo.setText("Archivo");

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(this::menuItemSalirActionPerformed);
        menuArchivo.add(menuItemSalir);

        jMenuBar1.add(menuArchivo);

        menuInstrumentoCuerda.setText("InstrumentoCuerda");

        menuItemAdicionarCuerda.setText("Adicionar InstrumentoCuerda");
        menuItemAdicionarCuerda.addActionListener(this::menuItemAdicionarCuerdaActionPerformed);
        menuInstrumentoCuerda.add(menuItemAdicionarCuerda);

        menuItemListarCuerda.setText("Listar InstrumentoCuerda");
        menuItemListarCuerda.addActionListener(this::menuItemListarCuerdaActionPerformed);
        menuInstrumentoCuerda.add(menuItemListarCuerda);

        menuItemConsultarCuerda.setText("Consultar InstrumentoCuerda");
        menuItemConsultarCuerda.addActionListener(this::menuItemConsultarCuerdaActionPerformed);
        menuInstrumentoCuerda.add(menuItemConsultarCuerda);

        menuItemEliminarCuerda.setText("Eliminar InstrumentoCuerda");
        menuItemEliminarCuerda.addActionListener(this::menuItemEliminarCuerdaActionPerformed);
        menuInstrumentoCuerda.add(menuItemEliminarCuerda);

        menuItemEditarInstrumentoCuerda.setText("Editar InstrumentoCuerda");
        menuItemEditarInstrumentoCuerda.addActionListener(this::menuItemEditarInstrumentoCuerdaActionPerformed);
        menuInstrumentoCuerda.add(menuItemEditarInstrumentoCuerda);

        jMenuBar1.add(menuInstrumentoCuerda);

        menuInstrumentoViento.setText("InstrumentoViento");

        menuItemAdicionarViento.setText("Adicionar InstrumentoViento");
        menuItemAdicionarViento.addActionListener(this::menuItemAdicionarVientoActionPerformed);
        menuInstrumentoViento.add(menuItemAdicionarViento);

        menuItemListarViento.setText("Listar InstrumentoViento");
        menuItemListarViento.addActionListener(this::menuItemListarVientoActionPerformed);
        menuInstrumentoViento.add(menuItemListarViento);

        menuItemConsultarViento.setText("Consultar InstrumentoViento");
        menuItemConsultarViento.addActionListener(this::menuItemConsultarVientoActionPerformed);
        menuInstrumentoViento.add(menuItemConsultarViento);

        menuItemEliminarViento.setText("Eliminar InstrumentoViento");
        menuItemEliminarViento.addActionListener(this::menuItemEliminarVientoActionPerformed);
        menuInstrumentoViento.add(menuItemEliminarViento);

        menuItemEditarViento.setText("Editar InstrumentoViento");
        menuItemEditarViento.addActionListener(this::menuItemEditarVientoActionPerformed);
        menuInstrumentoViento.add(menuItemEditarViento);

        jMenuBar1.add(menuInstrumentoViento);

        menuAyuda.setText("Ayuda");

        menuItemAutores.setText("Autores");
        menuItemAutores.addActionListener(this::menuItemAutoresActionPerformed);
        menuAyuda.add(menuItemAutores);

        jMenuItem1.setText("¿Como usarlo?");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        menuAyuda.add(jMenuItem1);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAdicionarCuerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdicionarCuerdaActionPerformed
        GUIAdicionarCuerda gui = new GUIAdicionarCuerda();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemAdicionarCuerdaActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemListarVientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarVientoActionPerformed
        GUIListarViento gui = new GUIListarViento();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemListarVientoActionPerformed

    private void menuItemAdicionarVientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdicionarVientoActionPerformed
        GUIAdicionarViento gui = new GUIAdicionarViento();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemAdicionarVientoActionPerformed

    private void menuItemAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAutoresActionPerformed
        JOptionPane.showMessageDialog(null, "Hecho por Antonio Lopez, Juan Cossio y Sebastian Londoño", "Autores", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemAutoresActionPerformed

    private void menuItemListarCuerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarCuerdaActionPerformed
        GUIListarCuerda gui = new GUIListarCuerda();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemListarCuerdaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "Tienes un menú para gestionar dos tipos de instrumentos: Cuerda y Viento. ", "Tutorial", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, "A partir de esto, puedes adicionar y listarlos teniendo en cuenta que adiciones primero el instrumento que desees", "Tutorial", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, "Suerte con eso y espero no encuentres bugs ;)", "Tutorial", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemConsultarCuerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarCuerdaActionPerformed
        GUIConsultarCuerda gui = new GUIConsultarCuerda();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemConsultarCuerdaActionPerformed

    private void menuItemConsultarVientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarVientoActionPerformed
         GUIConsultarViento gui = new GUIConsultarViento();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemConsultarVientoActionPerformed

    private void menuItemEliminarCuerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarCuerdaActionPerformed
        GUIEliminarCuerda gui = new GUIEliminarCuerda();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemEliminarCuerdaActionPerformed

    private void menuItemEditarInstrumentoCuerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarInstrumentoCuerdaActionPerformed
        GUIEditarCuerda gui = new GUIEditarCuerda ();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemEditarInstrumentoCuerdaActionPerformed

    private void menuItemEliminarVientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarVientoActionPerformed
        GUIEliminarViento gui = new GUIEliminarViento();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemEliminarVientoActionPerformed

    private void menuItemEditarVientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarVientoActionPerformed
        GUIEditarViento gui = new GUIEditarViento();
        gui.setVisible(true);
    }//GEN-LAST:event_menuItemEditarVientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuInstrumentoCuerda;
    private javax.swing.JMenu menuInstrumentoViento;
    private javax.swing.JMenuItem menuItemAdicionarCuerda;
    private javax.swing.JMenuItem menuItemAdicionarViento;
    private javax.swing.JMenuItem menuItemAutores;
    private javax.swing.JMenuItem menuItemConsultarCuerda;
    private javax.swing.JMenuItem menuItemConsultarViento;
    private javax.swing.JMenuItem menuItemEditarInstrumentoCuerda;
    private javax.swing.JMenuItem menuItemEditarViento;
    private javax.swing.JMenuItem menuItemEliminarCuerda;
    private javax.swing.JMenuItem menuItemEliminarViento;
    private javax.swing.JMenuItem menuItemListarCuerda;
    private javax.swing.JMenuItem menuItemListarViento;
    private javax.swing.JMenuItem menuItemSalir;
    // End of variables declaration//GEN-END:variables
}
